//
//  StoryboardExampleViewController.swift
//  SwiftyOnboardExample
//
//  Created by Jay on 3/27/17.
//  Copyright © 2017 Juan Pablo Fernandez. All rights reserved.
//

import UIKit
import SwiftyOnboard

class StoryboardExampleViewController: UIViewController {

    @IBOutlet weak var swiftyOnboard: SwiftyOnboard!
    
    
    
    
    var titleArray: [String] = ["Analyzer", "Stock Trend / Rating", "Top 10 Industries","StockAxis Top 50 Stocks","StockAxis Blogs","Latest Market News"]
    var subTitleArray: [String] = ["All financial numbers of listed companies now on your fingertips for an efficient and an exhaustive analysis of your favorite company.", "Get access of an exclusive system that analyses the trends of over 2000 stocks every day.", "Access to a daily updated list of the leading industries and the top companies in to those industries as well.","Get the list of the Top 50 ranked stocks generated by our innovative and robust Stock Rating System.","A hand-picked list of topics covering various aspects of fundamental investing enabling smarter invesment decision.","Quick access to all company specific and other business news"]
    
    //fileprivate let sectionTitles = ["Configurations", "Item Size", "Interitem Spacing", "Number Of Items"]
    // fileprivate let configurationTitles = ["Automatic sliding","Infinite"]
    
    //var ImageArray: [String] = ["trendratingmobile", "trendratingmobile", "toptenmobile","topfiftymobile","newsmobile"]
    fileprivate let imageNames = ["Analyzer.png","ChangeInTrend.png","Top10Industries.png","Top50.png","Blog.png","News.png"]
    fileprivate var numberOfItems = 6
    
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        swiftyOnboard.style = .light
        swiftyOnboard.delegate = self
        swiftyOnboard.dataSource = self
   //     swiftyOnboard.backgroundColor = UIColor(red: 46/256, green: 46/256, blue: 76/256, alpha: 1)
    }
    
    func handleSkip() {
        swiftyOnboard?.goToPage(index: 5, animated: true)
    }
    
    func handleContinue(sender: UIButton) {
        let index = sender.tag
        swiftyOnboard?.goToPage(index: index + 1, animated: true)
    }
}

extension StoryboardExampleViewController: SwiftyOnboardDelegate, SwiftyOnboardDataSource {
    
    func swiftyOnboardNumberOfPages(_ swiftyOnboard: SwiftyOnboard) -> Int {
        return numberOfItems
    }
    
    func swiftyOnboardPageForIndex(_ swiftyOnboard: SwiftyOnboard, index: Int) -> SwiftyOnboardPage? {
        let view = CustomPage.instanceFromNib() as? CustomPage
        
        if(index == 0)
        {
            view?.View1.backgroundColor = UIColor.black
            view?.View2.backgroundColor = UIColor.lightGray
            view?.View3.backgroundColor = UIColor.lightGray
            view?.View4.backgroundColor = UIColor.lightGray
            view?.View5.backgroundColor = UIColor.lightGray
            view?.View6.backgroundColor = UIColor.lightGray
            
            
        }
            
        else if(index == 1)
        {
            view?.View1.backgroundColor = UIColor.lightGray
            view?.View2.backgroundColor = UIColor.black
            view?.View3.backgroundColor = UIColor.lightGray
            view?.View4.backgroundColor = UIColor.lightGray
            view?.View5.backgroundColor = UIColor.lightGray
            view?.View6.backgroundColor = UIColor.lightGray
        }
            
        else if(index == 2)
        {
            view?.View1.backgroundColor = UIColor.lightGray
            view?.View2.backgroundColor = UIColor.lightGray
            view?.View3.backgroundColor = UIColor.black
            view?.View4.backgroundColor = UIColor.lightGray
            view?.View5.backgroundColor = UIColor.lightGray
            view?.View6.backgroundColor = UIColor.lightGray
        }
            
        else if(index == 3)
        {
            view?.View1.backgroundColor = UIColor.lightGray
            view?.View2.backgroundColor = UIColor.lightGray
            view?.View3.backgroundColor = UIColor.lightGray
            view?.View4.backgroundColor = UIColor.black
            view?.View5.backgroundColor = UIColor.lightGray
            view?.View6.backgroundColor = UIColor.lightGray
            
        }
        else if(index == 4)
        {
            view?.View1.backgroundColor = UIColor.lightGray
            view?.View2.backgroundColor = UIColor.lightGray
            view?.View3.backgroundColor = UIColor.lightGray
            view?.View4.backgroundColor = UIColor.lightGray
            view?.View5.backgroundColor = UIColor.black
            view?.View6.backgroundColor = UIColor.lightGray
        }
            
        else{
            view?.View1.backgroundColor = UIColor.lightGray
            view?.View2.backgroundColor = UIColor.lightGray
            view?.View3.backgroundColor = UIColor.lightGray
            view?.View4.backgroundColor = UIColor.lightGray
            view?.View5.backgroundColor = UIColor.lightGray
            view?.View6.backgroundColor = UIColor.black
            
        }
        
       // let view = CustomPage.instanceFromNib() as? CustomPage
     
            //On the first page, change the text in the labels to say the following:
              view?.ImageView.image = UIImage(named: imageNames[index])
            view?.TitleLabel.text = titleArray[index]
            view?.SubTitle.text = subTitleArray[index]
        
        return view
    }
    
    func swiftyOnboardViewForOverlay(_ swiftyOnboard: SwiftyOnboard) -> SwiftyOnboardOverlay? {
        let overlay = CustomOverlay.instanceFromNib() as? CustomOverlay
        overlay?.skip.addTarget(self, action: #selector(handleSkip), for: .touchUpInside)
        overlay?.buttonContinue.addTarget(self, action: #selector(handleContinue), for: .touchUpInside)
        return overlay
    }
    
    func swiftyOnboardOverlayForPosition(_ swiftyOnboard: SwiftyOnboard, overlay: SwiftyOnboardOverlay, for position: Double) {
        let overlay = overlay as! CustomOverlay
        let currentPage = round(position)
        overlay.pageControl.currentPage = Int(currentPage)
        overlay.buttonContinue.tag = Int(position)
        if currentPage == 0.0 || currentPage == 1.0 || currentPage == 2.0 || currentPage == 3.0 || currentPage == 4.0 {
            overlay.buttonContinue.setTitle("Continue", for: .normal)
            overlay.skip.setTitle("Skip", for: .normal)
            overlay.skip.isHidden = false
        } else {
            overlay.buttonContinue.setTitle("Get Started!", for: .normal)
            overlay.skip.isHidden = true
        }
    }
}
